on:
  push:
    branches: 
      - '*'

jobs:
  grep:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: ls -la
      
      - run: perl -nle 'print $1 if /<Version>(\S+)<\/Version>/' CelesteStudio.csproj
