on:
  push:
    branches: 
      - '*'

jobs:
  grep:
    runs-on: ubuntu-latest

    steps:
      - run: ls -la
      - run: grep --version
      - run: grep -Po '(?<=<Version>)\S+(?=<\\/Version>)' CelesteStudio.csproj
